install.packages("devtools")
install.packages("data.table")
install.packages("tidyverse")
install.packages("kableExtra")
install.packages("shinyWidgets")
install.packages("reactLog")
install.packages("sloop")
install.packages("DT")
install.packages("shinyFeedback")
install.packages("akima")
install.packages("ggrepel")

devtools::install_github("aaronmanderson3/rftk")
remotes::install_github("gadenbuie/regexplain")